name: flutter_form_example
description: "A new Flutter example project."

publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.10.0-75.1.beta

dependencies:
  flutter:
    sdk: flutter

  flutter_form_generator:
    path: ../
  cupertino_icons: ^1.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true